[workspace]
members = ["./crates/kernel", "./crates/os-runner", "crates/graphics"]
resolver = "3"

[workspace.dependencies]
bootloader_api = "0.11.13"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
