[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.11.13"

[package.metadata.bootimage]
# default-target = "x86_64-beyond.json"
default-target = "x86_64-unknown-none"
