[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
console = { path = "../console" }
keyboard = { path = "../drivers/keyboard" }
meta = { path = "../meta" }
memory = { path = "../memory" }
x86_64 = "0.15.4"
