[target.x86_64-unknown-none]
runner = "bootimage runner"

[alias]
kr = "run -p kernel"
#1
kb = "build -p kernel --target x86_64-unknown-none"
#2
or = "run -p os-runner"
#3
# qemu-system-x86_64 -drive file=target/bios.img,format=raw -no-reboot -no-shutdown
